services:
  train:
    # image: gcr.io/mythic-music-447818-m3/train:latest
    image: train:latest
    build:
      context: .
      dockerfile: dockerfiles/train.dockerfile
    container_name: trainer-container
    volumes:
      # - ./data:/data
      - ./models:/models
  
  evaluate:
    image: evaluate:latest
    build:
      context: .
      dockerfile: dockerfiles/evaluate.dockerfile
    volumes:
      - ./models:/models  # Mount models directory

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - train
    volumes:
      - ./models:/models  # Mount models directory
      - ./src:/src