_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 3
                - 8
                - 14
                - 16
                - 23
                - 35
                - 55
                - 62
            "4": 3.11.11
            "5": 0.19.3
            "6": 4.37.0
            "8":
                - 5
            "10":
                - 9
                - 17
            "12": 0.19.3
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 10
lr:
    value: 0.001
