_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 14
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.3
            "6": 4.37.0
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
