name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for training
      run: docker build . --file dockerfiles/train.dockerfile --tag train:$(date +%s)
    - name: Build the Docker image for evaluation
      run: docker build . --file dockerfiles/evaluate.dockerfile --tag evaluate:$(date +%s)